# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171127_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerar_notificacao', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='historico',
            name='acao',
            field=models.CharField(choices=[('0', 'Estava com fome'), ('1', 'Queria ir ao banheiro'), ('2', 'Estava com sono'), ('3', 'Estava com dor')], default='0', max_length=1),
        ),
    ]
