# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171128_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='gerar_notificacao',
            field=models.BooleanField(default=False),
        ),
    ]
